name: Copy
on: 
  push:
    branches: [ master ]
jobs:
  copy:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.PERSONAL_TOKEN}}
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: build/web/.
        dst_path: /public-flutter/
        dst_owner: himanshusharma89
        dst_repo_name: 100DaysOfFlutter
        dst_branch: test
        src_branch: master
        src_wiki: false
        dst_wiki: false
        username: himanshusharma89
        email: ranubhardwaj89@gmail.com
